CREATE TABLE users_auth (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    roles TEXT NOT NULL
);

CREATE TABLE jwks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id TEXT UNIQUE,
  jwk TEXT
);